 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/api/:_time')
    .get(function(req, res, next) {
      var time = (req.params._time)
      var options = {year: 'numeric', month: 'long', day: 'numeric'}
      var orig = new Date(time);
      if (orig == "Invalid Date") {
        naturalTime = null;
        unixTime = null;
      } else if (isNaN(time)) {
        var naturalTime = new Date(time);
        naturalTime = naturalTime.toLocaleDateString('en-us', options);
        var unixTime = new Date(time).getTime()/1000;
      } else {
        var unixTime = time;
        var naturalTime = new Date(time * 1000);
        naturalTime = naturalTime.toLocaleDateString('en-us', options);
      }
      
      res.json({unix: unixTime, natural: naturalTime});
    })

app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })

// Respond not found to all the wrong routes
app.use(function(req, res, next){
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});
